### ISSUE TITLE
How to parse in this case?

### ISSUE THREAD

**Issue by tudousponge** [kurtmckee/feedparser#177]
I'd like to parse this URL, but when I come across two elements with the same name within one entry, the later one seems to overwrite the former one:
<img width="796" alt="feedparse1" src="https://user-images.githubusercontent.com/49153433/61589328-f4cff380-abda-11e9-8131-24d3bd543573.png">
<img width="819" alt="feedparser2" src="https://user-images.githubusercontent.com/49153433/61589329-f4cff380-abda-11e9-9ba5-767f3a194179.png">
How can I parse them both?

**Comment by masklinn** [comment]
FWIW I don't think there's any way to do that aside from adding bespoke support for this namespace in feedparser.

In my understanding, currently feedparser assumes each element is a key mapping to a single element by default. The alternative would be to make everything into a multidict (but keep a "monodict" interface by default), but that probably wouldn't help with the oft reported performance and memory issues.

**Comment by masklinn** [comment]
FWIW I don't think there's any way to do that aside from adding bespoke support for this namespace in feedparser.

In my understanding, currently feedparser assumes each element is a key mapping to a single element by default. The alternative would be to make everything into a multidict (but keep a "monodict" interface by default), but that probably wouldn't help with the oft reported performance and memory issues.

**Comment by kurtmckee** [comment]
@masklinn Thanks for looking into this.

@tudousponge Sorry for the delay. The root issue here is that feedparser is NOT a generic XML parser -- it will not maintain all structures in a dictionary or list. At some point in the distant past, code was added to allow feedparser to handle unknown namespaces like the "trending searches" namespace `ht` in your example. However, this support was limited to ensure that unknown XML inputs would not result in massive unexpected memory usage. The consequence is that unknown namespaces, like `ht`, will only ever include the latest singular element.

Your report is part of a larger issue that needs to be addressed in feedparser's design: allow users to easily add new namespaces...then utterly disable all unknown namespace support in feedparser. It hasn't happened yet because I write code for my day job and simply haven't had the motivation to put in extra hours at night or on weekends to get this done. I'm open to patches, though!
