### ISSUE TITLE
Update references to feedparser being a single file module

### ISSUE THREAD

**Issue by eadmaster** [kurtmckee/feedparser#274]
[source](https://pythonhosted.org/feedparser/introduction.html)

> Universal Feed Parser is easy to use; the module is self-contained in a single file, feedparser.py

is it possible to download the whole module in a single file?

**Comment by kurtmckee** [comment]
@eadmaster, thanks for reporting this. pythonhosted.org is no longer accepting documentation updates so feedparser's docs have moved to ReadTheDocs. Please update bookmarks and references.

However, this text exists even in the current documentation so I'll remove that. Thanks again for reporting this!

**Comment by eadmaster** [comment]
ok. i understand... btw a single file amalgamation release would still be useful (including the dep `sgmllib3`).  
Any suggestion for a tool that could be used to produce such amalgamation?

**Comment by kurtmckee** [comment]
@eadmaster, thanks again for reporting this!

Regarding amalgamations, this is supported in Python already by way of zip imports and zip apps.

The Python standard library has a module called [zipapp](https://docs.python.org/3/library/zipapp.html) that you can check out, and you can also check out [zipimport](https://docs.python.org/3/library/zipimport.html). They're very helpful!

**Comment by masklinn** [comment]
@kurtmckee is there no way to make pythonhosted redirect traffic or at least bots to the official documentation on RTD? It remains by far the highest hit when looking for feedparser's docs in search engines (at least DDG and Google).

Even more frustratingly, aside from the pypi page for this project (which often places well) and more rarely the [conda package page](https://anaconda.org/anaconda/feedparser), very high hits on feedparser are:

* pythonista's docs, which links to pythonhosted
* the independent, completely outdated, and removed from github `universal-feedparser`

For the latter, maybe the author could be contacted to redirect or otherwise yield the project page to this more active fork?

**Comment by kurtmckee** [comment]
@masklinn Thanks for digging into this! It appears that there's a way to request redirects so pythonhosted is pointing at the latest docs. I'll need to submit a request and then it should redirect. I'll try to contact other services that you've mentioned to get other incoming links updated. Thanks!

**Comment by masklinn** [comment]
@kurtmckee my pleasure! and it's great news if pythonhosted can be pointed elsewhere.

I've no special access to any of those service, but do say if I can help with anything.
