### ISSUE TITLE
Get raw RSS feed

### ISSUE THREAD

**Issue by grubeli** [kurtmckee/feedparser#303]
I used feedparser to modify values in entries, is there a way to get raw RSS/xml string from feedparser parsed object?

**Comment by lemon24** [comment]
Not by using feedparser alone, it only does deserialization.

You can use something like [feedgen](https://pypi.org/project/feedgen/), though; here's [an example](https://github.com/lemon24/andgravity-generator/blob/1faa38dac3cb192811a50b40daf178c5ea1ff46a/gen/app.py#L173-L239) of feedgen in use. Instead of `page`, you would get data from `d.feed`, and instead of `children`, you would use the entries from `d.entries` (where `d` is the return value of `feedparser.paser()`).

(Unless @kurtmckee plans to support round-tripping feeds in the future, I think this can be closed.)

**Comment by kurtmckee** [comment]
@grubeli You can use the `requests` package or similar to make the HTTP request. This will give you access to the raw XML, and it can be passed into feedparser as well for parsing.

@lemon24 Thanks for contributing to this! You're right, I have no plans to do XMl->object->XML round-tripping.
