### ISSUE TITLE
Feature request : let us specify the encoding

### ISSUE THREAD

**Issue by louisameline** [kurtmckee/feedparser#31]
Hello again and thanks for the great work.

Unless I missed something, I think there is no way to tell Feedparser the feed encoding if we already know it. In my case, I process and convert the feed to utf8 in Node before passing it to Feedparser. The passed feed is in utf8 but the `encoding="window-1252"` attribute is still present in the feed content and causes Feedparser to fail. I'd be happy not to have to remove that attribute myself.

Thank you.

**Comment by kurtmckee** [comment]
@louisameline thanks for pointing this out. I'll think about how to implement this, but my gut is that if the encoding is already known perhaps it would be possible to send in a unicode string instead of a UTF8-encoded string. I think this would also help others who are using the requests module to manage the feed downloading, since it returns unicode strings. Would this be an acceptable possible solution?

My goal is to avoid adding another parameter to the `parse()` function.
