### ISSUE TITLE
RFE: move away from sgmllib module

### ISSUE THREAD

**Issue by kloczek** [kurtmckee/feedparser#313]
Looks like `feedparser` still is using `sgmllib` module
```console
[tkloczko@devel-g2v feedparser-6.0.10]$ grep -r sgmllib
NEWS:    * Issue 252 (running setup.py in Python 3 fails due to missing sgmllib)
NEWS:    * Issue 271 (monkey-patching sgmllib breaks other libraries)
NEWS:  from Unicode to raw strings before feeding data to sgmllib.SGMLParser;
docs/changes-30.rst:- fixed character encoding issues in BaseHTMLProcessor by tracking encoding and converting from Unicode to raw strings before feeding data to sgmllib.SGMLParser
feedparser/html.py:class _BaseHTMLProcessor(sgmllib.SGMLParser, object):
feedparser/html.py:    # with the code from sgmllib, the original code will execute in
feedparser/html.py:    # feedparser's scope instead of sgmllib's. This means that the
feedparser/html.py:    # they're declared above, not as they're declared in sgmllib.
feedparser/html.py:        goahead.__code__ = sgmllib.SGMLParser.goahead.__code__
feedparser/html.py:        goahead.func_code = sgmllib.SGMLParser.goahead.func_code
feedparser/html.py:        __parse_starttag.__code__ = sgmllib.SGMLParser.parse_starttag.__code__
feedparser/html.py:        __parse_starttag.func_code = sgmllib.SGMLParser.parse_starttag.func_code
feedparser/html.py:            return sgmllib.SGMLParser.parse_declaration(self, i)
feedparser/html.py:        except sgmllib.SGMLParseError:
feedparser/sgml.py:import sgmllib
feedparser/sgml.py:    'sgmllib',
feedparser/sgml.py:# sgmllib defines a number of module-level regular expressions that are
feedparser/sgml.py:# the variables directly in sgmllib, they're defined here using the same
feedparser/sgml.py:# names, and the compiled code objects of several sgmllib.SGMLParser
feedparser/sgml.py:# feedparser's scope instead of sgmllib's scope.
feedparser/sgml.py:entityref = sgmllib.entityref
feedparser/sgml.py:incomplete = sgmllib.incomplete
feedparser/sgml.py:interesting = sgmllib.interesting
feedparser/sgml.py:shorttag = sgmllib.shorttag
feedparser/sgml.py:shorttagopen = sgmllib.shorttagopen
feedparser/sgml.py:starttagopen = sgmllib.starttagopen
feedparser/sgml.py:        # Overriding the built-in sgmllib.endbracket regex allows the
setup.py:    install_requires=['sgmllib3k'],
tests/runtests.py:    """Test the sgmllib-based parser by manipulating feedparser into believing no XML parsers are installed"""
```
Issue is that this module seems is no maintained since 2010 https://pypi.org/project/sgmllib3k/ (home page of thah module no longer exist as well).
I'm not sure which one module would be the best as replacement but probably `lxml`.

**Comment by kurtmckee** [comment]
feedparser already uses lxml if it's installed, but lxml is not a replacement for sgmllib (which was part of the Python standard library until Python 3).

**Comment by kloczek** [comment]
So it is not possible to remove that `sgmllib3k` dependency? 🤔

**Comment by kurtmckee** [comment]
~20 years ago, feedparser was built on top of sgmllib (which was part of the Python 2 standard library). Over time it gained support for actual XML parsing in strict mode, but it would always fallback to sgmllib as soon as an XML parser would crash due to malformed XML. And there is _always_ malformed XML on the open internet.

Although feedparser will use libxml2 as its XML parser if it's installed, it continues to rely on sgmllib for parsing corrupt XML. libxml2 -- and therefore lxml -- maintains its own algorithms for recovering from corrupt XML, and data can completely disappear within its C code before it ever bubbles up to feedparser. sgmllib handles corrupt XML by simply firing various start- and end-tag handlers in whatever order the tags are encountered. feedparser then tries to figure out what it should do with those tags.

You may not be aware of how it comes across, but the attitude in each of the issues you've reported here has seemed to be "I don't like something, so you should re-architect feedparser."

I should rip out tox because it's slow? tox generates a consistent environment that matches dependencies, versions, and environments that I'm willing to support. It is indeed slow to test 6x Python versions and 2x dependency possibilities, plus documentation, plus mypy. It has helped catch problems prior to releases, though.

I should rip out sgmllib3k because it's 10 years old? It has no dependencies except Python's `re` module, and it's been the bedrock of feedparser's support for malformed XML for almost 20 years.

Please consider that I do this for fun. Jabbing at me through a textbox doesn't start a constructive conversation, and it won't move me to spend weeks of my free time re-architecting anything.

I encourage you to keep filing tickets, but please remember that feedparser is almost 20 years old (so it has a legacy of decisions that brought it to its current state), I've been maintaining it for almost 12 years (so I have some knowledge of how it works, and why), and treat me like a person who genuinely wants the software to improve.

**Comment by kloczek** [comment]
I know all of that. Issue is that below part
```consile
setup.py:    install_requires=['sgmllib3k'],
```
is used unconditionally.
Other thing is: what is the sense to keep still in source tree today code which may use `sgmllib3k`? 🤔

**Comment by kurtmckee** [comment]
It's unconditional because sgmllib3k is required.

The code that uses sgmllib3k exists because it's necessary for parsing malformed XML.

**Comment by kloczek** [comment]
Is it anywhere ticket opened or closed for that `lxlml` malfunction?

**Comment by kurtmckee** [comment]
I don't think it's a malfunction. It's just how libxml2 works.

**Comment by kloczek** [comment]
Moment so are blaming libxml2 without any conversation with libxml2 maintainers? 🤔 
Maybe it would be better to just ask how to handle exact cases?

**Comment by kurtmckee** [comment]
> blaming libxml2

Nope! That's not what I've said or written.
