### ISSUE TITLE
adding url prefix to id tag

### ISSUE THREAD

**Issue by sayginify** [kurtmckee/feedparser#323]
I've tried feedparser with following url : 
http://128.199.162.51/feed

normally, within the xml file there's id tags such as <id>72122</id>
but when I parse them, within the feed entries, it becomes http://128.199.162.51/72122 

any idea what might be the cause?

**Comment by kurtmckee** [comment]
This is happening because feedparser is trying hard to do the right thing, which in this case is to assume that the feed is declared as RSS but is using elements from the Atom specification.

The `<id>` elements are assumed to be Atom ID's. feedparser is assuming they are relative URI's, and is normalizing them to maintain uniqueness.

That feed smells like its author used a feed generator instead of an XML generator and injected arbitrary content. If this is the only XML document you're wanting to parse, you might benefit from using an XML parser instead of feedparser.

**Comment by sayginify** [comment]
thanks a lot for the quick and detailed response.
