### ISSUE TITLE
Checking bozo will cause parser to fail (not checking will parse fine)

### ISSUE THREAD

**Issue by jake1164** [kurtmckee/feedparser#66]
Simple test case:
    import feedparser
    import json

    info = {}
    parser = feedparser.parse('http://feeds.feedburner.com/codinghorror')

    #if parser.bozo == 1:
    #    info['bozo_message'] = parser.bozo_exception

    info['title'] = parser.feed['title']
    print(json.dumps(info))

With the bozo check commented out this runs fine and prints the json string with the title, uncomment the bozo check and you get:

    SAXParseException('Input is not proper UTF-8, indicate encoding !\nBytes: 0xE2 0x80 0x99 0x73\n',) is not JSON serializable

I would expect this to work the same regardless of checking the bozo exception.

**Comment by kurtmckee** [comment]
It does work. The problem is that the SAXParseException cannot be serialized into JSON format. feedparser returns a bunch of information that uses simple types like strings and tuples, but it's not guaranteed that the results can be serialized into JSON.

Try importing and using ``pprint.pprint(info)`` instead of ``print(json.dumps(info))`` for comparison.
