### ISSUE TITLE
New PyPi release

### ISSUE THREAD

**Issue by nsoranzo** [kurtmckee/feedparser#99]
Hi @kurtmckee,
we are using feedparser in [Galaxy](https://github.com/galaxyproject/galaxy) and we are soon going to need fully Python3-compatible dependencies. Can you do a new release including sgmllib3k and Python3.5 support,  please?

**Comment by asherf** [comment]
any news on this @kurtmckee ?

**Comment by buhtz** [comment]
See #108

**Comment by kurtmckee** [comment]
I've release a 6.0.0b1 beta to PyPI. I'm looking for feedback. Thanks!

**Comment by brondsem** [comment]
Nice to see this project still moving along!  I am seeing a parsing issue on 6.0.0b1 (both py2 & py3):

```
>>> import feedparser
>>> x = feedparser.parse('http://www.liferay.com/community/blogs/all/-/blogs_stream/aggregate/rss')
>>> x.entries
[]
>>> x.bozo
1
>>> x.bozo_exception
SAXParseException('mismatched tag')
```

With 5.2.1 installed, this particular feed parses ok.  The feed appears to be valid enough: http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fwww.liferay.com%2Fcommunity%2Fblogs%2Fall%2F-%2Fblogs_stream%2Faggregate%2Frss

Also, `feedparser.__version__` still is '5.2.1' in the beta release

**Comment by kurtmckee** [comment]
Thanks for the feedback! I'll look into this asap.

**Comment by kurtmckee** [comment]
I've released 6.0.0b2. Please let me know if there are any major issues you encounter!

**Comment by kurtmckee** [comment]
@brondsem the URL is redirecting permanently to another location. It appears it's jumping from HTTP to HTTPS and is jumping across domains. This is perhaps the root cause but I'm not targeting any fixes for feedparser's HTTP support and will be completely removing its support in the future.

Please use a dedicated HTTP client library like requests.

**Comment by kurtmckee** [comment]
@nsoranzo 6.0.0b3 has been released. Please let me know if you encounter any serious problems.

**Comment by Ekleog** [comment]
Hey! Any news on releasing 6.0.0? At rss2email we're thinking it'd be a good thing to update to a newer feedparser (https://github.com/rss2email/rss2email/issues/73), but we probably won't be able to do it until an actual release is cut, as depending on a beta is too risky due to breaking change risks (especially as I seem to read that http(s) support will maybe be dropped altogether in the future).

**Comment by kurtmckee** [comment]
6.0.0 has been released today. Note that there are likely breaking changes. Please test in your dev environments and pin your requirements files to specific versions if you encounter issue. File tickets as needed.

Note also that it is no longer possible to update the documentation on `pythonhosting`, and someone has already taken the `feedparser` project name on Read the Docs. I have emailed the person and am hopeful that they will respond soon. At this time, however, there is no authoritative place to upload current documentation.

**Comment by Ekleog** [comment]
Great, thank you! :D
